### ISSUE TITLE
查询百度注册信息的API

### ISSUE THREAD

**Issue by ChenZhongPu** [ff0000team/Sreg#4]
如何知道百度注册信息Request的URL？

**Comment by evi1m0** [comment]
![http://ww4.sinaimg.cn/large/c334041bgw1eqfjub1wq1j20mq0ew3zv.jpg](http://ww4.sinaimg.cn/large/c334041bgw1eqfjub1wq1j20mq0ew3zv.jpg)

**Comment by ChenZhongPu** [comment]
谢谢。我get请求 https://passport.baidu.com/v2/?regphonecheck&phone=18789482356 返回

```
({"errno":130020,"index":null,"errmsg":"\u624b\u673a\u53f7\u5df2\u88ab\u6ce8\u518c\uff0c\u8bf7\u76f4\u63a5\u767b\u5f55\u6216\u66f4\u6362\u624b\u673a\u53f7\u6ce8\u518c"})
```

**Comment by evi1m0** [comment]
[https://github.com/ff0000team/Sreg/commit/a2bc908846af74f672c3a01d710b7187f05a7a82](https://github.com/ff0000team/Sreg/commit/a2bc908846af74f672c3a01d710b7187f05a7a82)
